apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rpi-surveillance
  namespace: rpi-surveillance
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rpi-stream.cowlab.org`)
      kind: Rule
      services:
        - name: rpi-surveillance
          port: 5173
    - kind: Rule
      match: Host(`rpi-stream.cowlab.org`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: rpi-surveillance
          port: 5173
          scheme: h2c
  tls:
    secretName: cowlab-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rpi-stream-cert
  namespace: rpi-surveillance
spec:
  secretName: cowlab-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.cowlab.org"
  dnsNames:
  - "cowlab.org"
  - "*.cowlab.org"