services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    devices:
      - /dev/video0:/dev/video0
    privileged: true  
    restart: unless-stopped

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 5173:5173
    # depends_on:
    #   - server
    restart: unless-stopped
